version: "3.8"

services:
  app:
    container_name: work-scout
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true
